services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: book_social_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bsn_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bsn.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - bsn_network
  maildev:
    image: maildev/maildev
    container_name: mail-dev-bsn
    restart: unless-stopped
    ports:
      - "1080:1080"  # Web UI
      - "1025:1025"  # SMTP Server
    networks:
      - bsn_network
networks:
  bsn_network:
    driver: bridge
volumes:
  postgres_data:
    driver: local